### PR TITLE
fix: grammar :)))))

### PR DESCRIPTION
**Pull request by tobycm**

### CODE REVIEW

**Comment by tobycm** [comment]
ai chỉnh setting merge vs protected branch v
aaaaaaaaa

**Review by pdt1806 — APPROVED** [review]
oh yea riel

**Comment by pdt1806** [comment]
btw it’s me

**Comment by code-ga** [comment]
Btw not me

**Comment by tobycm** [comment]
lmao ok

**Comment by code-ga** [comment]
> lmao ok

ông thêm whitelist được mà

**Pull request merged**
